name: Publish RSS feeds to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '00 * * * *'
  workflow_dispatch:

env:
  CI: true

jobs:
  publish-feeds:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Playwright
        uses: microsoft/playwright-github-action@v1

      - name: Install Firefox
        run: npx playwright install firefox

      - name: Run feed-me-up-scotty with retries
        run: |
          npx feed-me-up-scotty || npx feed-me-up-scotty || npx feed-me-up-scotty

      - name: Deploy to GitHub Pages
        run: |
          # Git 사용자 설정
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          # 원격 저장소 추가 및 최신 내용 가져오기
          git remote add gh-pages-remote https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch --no-recurse-submodules

          # 오래된 worktree 정보 정리
          git worktree prune

          # 기존에 './gh-pages' 디렉토리가 존재하면 강제로 제거합니다.
          if [ -d "./gh-pages" ]; then
            echo "기존의 ./gh-pages 디렉토리가 존재하므로 강제로 제거합니다."
            git worktree remove -f ./gh-pages || rm -rf ./gh-pages
          fi

          # gh-pages worktree 추가
          git worktree add ./gh-pages gh-pages

          # gh-pages 디렉토리로 이동 후 파일 업데이트
          cd gh-pages
          git rm -r .
          cp -r ../public/. .
          git add .
          git commit --message="Deploying to GitHub Pages from $GITHUB_SHA"
          git push gh-pages-remote gh-pages:gh-pages
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}